Authorpage
dispersal/CMPUT404-project-socialdistribution pull request #36
Opened 2019-03-14 22:10 UTC by FordMcLeod

please squash me. adds author/id/posts functionality, refactored friends logic.

2019-03-14 23:58 UTC, MichaelParadis requested changes

2019-03-14 23:58 UTC, MichaelParadis commented on posts/helpers.py
> +        except User.DoesNotExist:
This is worry some I will look into it

2019-03-14 23:58 UTC, MichaelParadis commented on posts/urls.py
> +    path('follow/<authorid>', FollowView.as_view(),name='follow'),
end url in /

2019-03-14 23:58 UTC, MichaelParadis commented on posts/urls.py
> +    path('author/<authorid>/posts', FrontEndAuthorPosts.as_view(), name='frontauthorposts'),
End url in /

2019-03-14 23:58 UTC, MichaelParadis commented on posts/helpers.py
> +        except User.DoesNotExist:
Think this should be a global exception incase an invalid uuid is passed. Also we should return false and let the caller deal with the not found behavior

2019-03-14 23:58 UTC, MichaelParadis commented on posts/views.py
> +class FriendRequestView(views.APIView):
Pretty sure this is duplicating an already existing

2019-03-14 23:58 UTC, MichaelParadis commented on posts/views.py
> +class FollowReqListView(views.APIView):
Double added.

2019-03-14 23:58 UTC, MichaelParadis commented on posts/views.py
> +    def get_user(self, pk):
This looks double added.

2019-03-14 23:58 UTC, MichaelParadis commented on posts/views.py
> -# def checkFOAF(request, userid,authorid):
Did you mean to delete this?

2019-03-15 00:06 UTC, FordMcLeod commented on posts/views.py
> -# def checkFOAF(request, userid,authorid):
yes

2019-03-15 00:15 UTC, merged