Feature/gh activity
dispersal/CMPUT404-project-socialdistribution pull request #78
Opened 2019-03-25 04:42 UTC by tlaz4

2019-03-25 15:55 UTC, MichaelParadis submitted a review, later dismissed

2019-03-25 15:55 UTC, MichaelParadis commented on posts/templates/author/author_posts.html
> +        {% if user.username == author.username %}
For multi node stuff we should be checking user.id == author.id

2019-03-25 15:55 UTC, MichaelParadis commented on posts/static/author/author_posts.js
> +                "X-CSRFToken": csrf,
Please add a todo to update to use basic auth. I have changed some things for mr worldwide and will need to update your stuff to get it working

2019-03-25 15:56 UTC, MichaelParadis requested changes
Please update based on the comments I have made on the other review.

2019-03-26 01:03 UTC, tlaz4 commented
Refactored JS for posting, github pulling is complete

2019-03-26 23:15 UTC, MichaelParadis approved these changes

2019-03-26 23:15 UTC, merged